#!/bin/sh -e

BIN=./shorten
SHN=example.shn
WAV=example.wav

[ -x ${BIN} ] || { echo ${BIN} not found ; exit 1 ; }
[ -r ${SHN} ] || { echo ${SHN} unreadable ; exit 1 ; }

$BIN -x $SHN $WAV && $BIN -v 2 -t wav $WAV - | cmp - $SHN

for options in \
	"-a2      -t s16"	\
	"-b1024   -t u16"	\
	"-a1024   -t s16x"	\
	"-b 4     -t u16x"	\
	"-m 0     -t s16hl"	\
	"-m 32    -t s16hl"	\
	"-v 0     -t s16hl"	\
	"-v 1     -t s16hl"	\
	"-v 2     -t s16hl"	\
	"-p1      -t s16hl"	\
	"-p16     -t s16hl"	\
	"-p16 -v2 -t s16hl"	\
	"-tulaw"		\
	"-talaw"		\
	"-ts8"			\
	"-tu8"			\
	"-ts16"			\
	"-tu16"			\
	"-tu16x"		\
	"-ts16hl"		\
	"-tu16hl"		\
	"-ts16lh"		\
	"-tu16lh"		\
	"-c2 -tulaw"		\
	"-c2 -talaw"		\
	"-a340 -c16"		\
	"-c2 -p4 -tu16 -b5"	\
	"-v2 -t ulaw"		\
	"-v2 -t alaw"		\
; do
	$BIN $options $WAV - | $BIN -x | cmp - $WAV
done

for q in 1 2 3 ; do
	TMP="/tmp/$WAV-q$q.shn"
	$BIN -q $q $WAV $TMP
	$BIN -x $TMP - | $BIN       | cmp - $TMP
	$BIN -x $TMP - | $BIN -q $q | cmp - $TMP
done

$BIN -r3 $WAV $TMP

rm -f $WAV $TMP
